services:
  frontend:
    stdin_open: true
    tty: true
    image: wmanintu/portfolio:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
